#config.py
API_KEY = 'ADD_YOUR_KEY_HERE'
API_SECRET_KEY = 'ADD_YOUR_SECRET_KEY_HERE'
ACCESS_TOKEN = 'ADD_YOUR_ACCESS_TOKEN'
ACCESS_TOKEN_SECRET = 'ADD_YOUR_ACCESS_TOKEN_SECRE'
BEARER_TOKEN = 'ADD_YOUR_BEARER_TOKEN'